export const brand = [
    { value: 'Todos', label: 'Todos' },
    { value: 'Lattafa', label: 'Lattafa' },
    { value: 'Armaf', label: 'Armaf' },
    { value: 'Carolina Herrera', label: 'Carolina Herrera' },
    { value: 'Bvlgary', label: 'Bvlgary' },
    { value: 'Moschino', label: 'Moschino' },
    { value: 'Afnan', label: 'Afnan' },
    { value: 'Ariana Grande', label: 'Ariana Grande' },
    { value: 'Dior', label: 'Dior' },
    { value: 'Escada', label: 'Escada' },
    { value: 'Chanel', label: 'Chanel' },
    { value: 'Victorinox', label: 'Victorinox' },
    { value: 'Paco Rabanne', label: 'Paco Rabanne' },
    { value: 'Hugo Boss', label: 'Hugo Boss' },
    { value: 'Lacoste', label: 'Lacoste' },
    { value: 'Tommy Hilfiger', label: 'Tommy Hilfiger' },
    { value: 'Victoria Secret', label: 'Victoria Secret' },
    { value: 'LEau dIssey', label: 'LEau dIssey' },
    { value: 'Lancome', label: 'Lancome' },
    { value: 'MontBlanc', label: 'MontBlanc' },
    { value: 'Britney Spears', label: 'Britney Spears' },
    { value: 'Dolce & Gabbane', label: 'Dolce & Gabbane' },
    { value: 'Montale Paris', label: 'Montale Paris' },
    { value: 'Guess', label: 'Guess' },
    { value: 'Creed', label: 'Creed' },
    { value: 'Valentino', label: 'Valentino' },
]