export const perfums = [
  {
    id: 1,
    name: 'Club de nuit intense',
    brand: 'Armaf',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/club_de_nuit_intense.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 12,
    name: 'Valentino born in roma',
    brand: 'Paris Hilton',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Valentino_born_in_roma.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 17,
    name: '212 vip Rose',
    brand: 'Carolina Herrera',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/212_vip_rose.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 3,
    name: 'Aqva Marine',
    brand: 'Bvlgari',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Bvlgari-aqva-marine.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 4,
    name: '9 PM',
    brand: 'Afnan',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Afnan-9-PM-2.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 5,
    name: '9 AM',
    brand: 'Afnan',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Afnan-9-am.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 6,
    name: 'Cloud',
    brand: 'Ariana Grande',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Cloud.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 11,
    name: 'Sauvage',
    brand: 'Dior',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Sauvage.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 7,
    name: 'Omnia Coral',
    brand: 'Bvlgari',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/bvlgari-omnia-coral.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 8,
    name: 'Sorbetto Rosso',
    brand: 'Escada',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/sorbetto-rosso.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 2,
    name: 'Emethyst',
    brand: 'lattafa',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Emethyst.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 9,
    name: 'Bleu Chanel',
    brand: 'Chanel',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/bleu_channel.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 10,
    name: 'Swiss Army',
    brand: 'Victorinox',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Swiss_army.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 13,
    name: 'One Million Lucky',
    brand: 'paco rabanne',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/one_million_lucky.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 14,
    name: '212 vip black',
    brand: 'Carolina Herrera',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/212_vip_black.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 15,
    name: 'Hugo Boss Unlimited',
    brand: 'Carolina Herrera',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Hugo_boss_unlimited.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 16,
    name: 'Invictus Legend',
    brand: 'Carolina Herrera',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/invictus_legend.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 18,
    name: 'Issey Miyake',
    brand: "L'Eau d'Issey",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Issey_miyake.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 19,
    name: 'Tommy Girl',
    brand: "Tommy Hilfiger",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/tommy_girl.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 20,
    name: 'Tommy',
    brand: "Tommy Hilfiger",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/tommy.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 21,
    name: 'Lacoste Essential',
    brand: "Lacoste",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/lacoste_essential.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 22,
    name: 'Lacoste Red',
    brand: "Lacoste",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/lacoste_red.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 23,
    name: 'La Vida es Bella',
    brand: "Lancome",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/la_vida_es_bella.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 23,
    name: 'Coconut',
    brand: "Victoria Secret",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/coconut.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 24,
    name: 'One Million Elixir',
    brand: "Paco Rabanne",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/one_million_elixir.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 25,
    name: 'Starwalker',
    brand: "MontBlanc",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/starwalker.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 26,
    name: '212 Sexy',
    brand: "Carolina Herrera",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/212_sexy.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 27,
    name: 'Dior Homme',
    brand: "Dior",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/dior_homme.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 28,
    name: 'Fantasy',
    brand: "Britney spears",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/fantasy.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 29,
    name: 'Arabians Tonka',
    brand: "Montale Paris",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/montale.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 30,
    name: 'Pure xs',
    brand: "Paco Rabanne",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/pure_xs.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 31,
    name: 'Devotion',
    brand: "Dolce & Gabbane",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/devotion.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 32,
    name: 'Guess',
    brand: "Eau De Parfum",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/guess.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 33,
    name: 'Phantom',
    brand: "Paco Rabanne",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Phantom.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 34,
    name: 'Miss Dior',
    brand: "Dior",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/miss_dior.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 35,
    name: 'Juice Berry (BomBomBum)',
    brand: "Victoria Secret",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/juice_berry.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 36,
    name: '212 Vip',
    brand: "Carolina Herrera",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/212_vip.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 37,
    name: 'Arrurru',
    brand: "Naturals",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Arrurru.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer y Niños',
  },
  {
    id: 38,
    name: 'perfumero',
    brand: "perfumero",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/perfumero.png',
    stock: 4,
    category: 'perfums',
    gender: 'Unisex',
  },
  {
    id: 39,
    name: 'Creed Aventus',
    brand: "Creed",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/creed_aventus.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 40,
    name: 'Bad Boy',
    brand: "Carolina Herrera",
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/bad_boy.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
];
