export const perfums = [
  {
    id: 1,
    name: 'Club de nuit intense',
    brand: 'Armaf',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/club_de_nuit_intense.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 12,
    name: 'Valentino born in roma',
    brand: 'Paris Hilton',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Valentino_born_in_roma.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 3,
    name: 'Aqva Marine',
    brand: 'Bvlgari',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Bvlgari-aqva-marine.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 4,
    name: '9 PM',
    brand: 'Afnan',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Afnan-9-PM-2.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 5,
    name: '9 AM',
    brand: 'Afnan',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Afnan-9-am.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 6,
    name: 'Cloud',
    brand: 'Ariana Grande',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Cloud.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 11,
    name: 'Sauvage',
    brand: 'Dior',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Sauvage.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 7,
    name: 'Omnia Coral',
    brand: 'Bvlgari',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/bvlgari-omnia-coral.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 8,
    name: 'Sorbetto Rosso',
    brand: 'Escada',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/sorbetto-rosso.png',
    stock: 4,
    category: 'perfums',
    gender: 'Mujer',
  },
  {
    id: 2,
    name: 'Emethyst',
    brand: 'lattafa',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Emethyst.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 9,
    name: 'Bleu Chanel',
    brand: 'Chanel',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/bleu_channel.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 10,
    name: 'Swiss Army',
    brand: 'Victorinox',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Swiss_army.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 13,
    name: 'One Million Lucky',
    brand: 'paco rabanne',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/one_million_lucky.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 14,
    name: '212 vip black',
    brand: 'Carolina Herrera',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/212_vip_black.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
  {
    id: 15,
    name: 'Hugo Boss Unlimited',
    brand: 'Carolina Herrera',
    description: 'i like it',
    price: 15000,
    imageUrl: '../../../assets/images/Hugo_boss_unlimited.png',
    stock: 4,
    category: 'perfums',
    gender: 'Hombre',
  },
];
